// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhejzgirwmghqbltapqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhoZWp6Z2lyd21naHFibHRhcHFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MDAyMzAsImV4cCI6MjA2ODM3NjIzMH0.UJiiEOVrbQ-TJQU9qM2P8dxMmgR35UNEfuLcGxHzK8s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});