// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://quhktmkvlhaycxddprzy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1aGt0bWt2bGhheWN4ZGRwcnp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MDY4MjcsImV4cCI6MjA2ODM4MjgyN30.NCRrgGqdit40JxOW-ZYdJQQ2HLPp1sbEIZJu1lhgZ4A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});